In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("/content/drive/MyDrive/cars.csv")
data

    Car;MPG;Cylinders;Displacement;Horsepower;Weight;Acceleration;Model;Origin
0    STRING;DOUBLE;INT;DOUBLE;DOUBLE;DOUBLE;DOUBLE;...
1    Chevrolet Chevelle Malibu;18.0;8;307.0;130.0;3...
2    Buick Skylark 320;15.0;8;350.0;165.0;3693.;11....
3    Plymouth Satellite;18.0;8;318.0;150.0;3436.;11...
4    AMC Rebel SST;16.0;8;304.0;150.0;3433.;12.0;70;US
..                                                 ...
402  Ford Mustang GL;27.0;4;140.0;86.00;2790.;15.6;...
403  Volkswagen Pickup;44.0;4;97.00;52.00;2130.;24....
404  Dodge Rampage;32.0;4;135.0;84.00;2295.;11.6;82;US
405    Ford Ranger;28.0;4;120.0;79.00;2625.;18.6;82;US
406     Chevy S-10;31.0;4;119.0;82.00;2720.;19.4;82;US

[407 rows x 1 columns]

In [3]:
data.shape

(407, 1)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 1 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Car;MPG;Cylinders;Displacement;Horsepower;Weight;Acceleration;Model;Origin  407 non-null    object
dtypes: object(1)
memory usage: 3.3+ KB

In [5]:
data.isnull()

     Car;MPG;Cylinders;Displacement;Horsepower;Weight;Acceleration;Model;Origin
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
..                                                 ...
402                                              False
403                                              False
404                                              False
405                                              False
406                                              False

[407 rows x 1 columns]

In [6]:
data.isna().sum()

Car;MPG;Cylinders;Displacement;Horsepower;Weight;Acceleration;Model;Origin    0
dtype: int64

In [9]:
data['C'].unique()

KeyError: ignored